server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: "admin"
    url: jdbc:postgresql://localhost:5432/postgres
    username: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always